### ISSUE TITLE
Dockerised localhost deployment

### ISSUE THREAD

**Issue by myyong** [alan-turing-institute/gateway#43]
## Goal 

All services to be in their own docker containers.

## Acceptance criteria

- [x] entire setup loads with single `docker-compose up` command
- [x] use `-p, --project-name NAME` to ensure that network names are consistent (for example if we run `docker-compose` from gateway we get different names to when we run docker-compose from the gateway-openfoam subdirectory)

**Comment by masonlr** [comment]
Good reference: for submodules and docker workflow:

https://github.com/abdes/submodule-docker-dev-workflow

**Comment by masonlr** [comment]
This issue should be worked on in tandem with #22

**Comment by masonlr** [comment]
@klapaukh if we go down the route of git submodules and a top-level `docker-compose.yml` file, what then is the role of the individual `docker-compose.yml` files in each repository? 

For example, is the data-model's own `docker-compose.yml` going to be needed in testing?
Is there ever a case where we only want to run `docker-compose up` on a subset of the repos? For example, you might be working on the job-manager and might only want the immediate upstream and downstream components to be up, i.e. don't need the front-end to be up?

**Comment by masonlr** [comment]
Or, do we get all this for free via the `depends_on` entries?

**Comment by masonlr** [comment]
Open question regarding configuration. Suggestion is to point to a config file in the `docker-compose.yml` file. See this pattern: https://testdriven.io/part-one-docker-config

This way we can swap from development to production config files by editing the compose file.

TODO: determine the best way that this interacts with github. We don't want to commit secrets, so need a template config file. Each user is responsible for filling out the actual config file (and this process should be documented in the readme). We don't want `git pull` to clobber the config file.
