### ISSUE TITLE
Use login authentication tokens in all API calls

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/gateway#61]
## Goal 
Require use of token to make API calls

## Acceptance criteria
API no longer accepts requests without valid token.

## Out of scope
Log off from front end only.

## Implementation notes
- [x] Frontend to re-enable authentication login, store in local storage.
- [x] Middleware to check token before accepting requests.
- [x] Dockerised Flask app to authenticate.

**Comment by masonlr** [comment]
Aiming to call the gateway-auth /auth/status endpoint for authorisation check. Will aim to implement this using a resource method decorator described in the flask restful documentation: http://flask-restful.readthedocs.io/en/0.3.5/extending.html#resource-method-decorators

**Comment by masonlr** [comment]
This has been implemented as https://github.com/alan-turing-institute/gateway-auth.

The authentication is activated by alan-turing-institute/gateway-middleware#23.
